// This file is autogenerated. Changes will be overwritten.
#include "UYX5XTB5RZ/moc_InspectorPanel.cpp"
#include "UYX5XTB5RZ/moc_MainWindow.cpp"
#include "UYX5XTB5RZ/moc_PageView.cpp"
#include "UYX5XTB5RZ/moc_ThumbnailPanel.cpp"
#include "UYX5XTB5RZ/moc_Toolbar.cpp"
