set(lupdate_project_file "C:/Users/shche/free-pdf-editor/CMakeLists.txt")
set(lupdate_translations "C:/Users/shche/free-pdf-editor/src/translations/pdfditor_en_US.ts;C:/Users/shche/free-pdf-editor/src/translations/pdfditor_es.ts;C:/Users/shche/free-pdf-editor/src/translations/pdfditor_fr.ts;C:/Users/shche/free-pdf-editor/src/translations/pdfditor_de.ts;C:/Users/shche/free-pdf-editor/src/translations/pdfditor_cs.ts;C:/Users/shche/free-pdf-editor/src/translations/pdfditor_pl.ts;C:/Users/shche/free-pdf-editor/src/translations/pdfditor_ru.ts")
set(lupdate_include_paths "")
set(lupdate_sources "")
set(lupdate_subproject_count 10)

set(lupdate_subproject1_source_dir "C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject1_include_paths "C:/Users/shche/free-pdf-editor/build_mingw/src/overlay_autogen/include;C:/Users/shche/free-pdf-editor/src;C:/Qt/6.10.2/mingw_64/include/QtCore;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/mkspecs/win32-g++;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtGui;C:/Qt/6.10.2/mingw_64/include")
set(lupdate_subproject1_sources "C:/Users/shche/free-pdf-editor/build_mingw/src/overlay_autogen/mocs_compilation.cpp;overlay/OverlayObject.h;overlay/AnnotationObject.h;overlay/AnnotationObject.cpp;overlay/TextEditObject.h;overlay/TextEditObject.cpp;overlay/ImageObject.h;overlay/ImageObject.cpp;overlay/ShapeObject.h;overlay/ShapeObject.cpp;C:/Users/shche/free-pdf-editor/build_mingw/src/overlay_autogen/timestamp;C:/Users/shche/free-pdf-editor/build_mingw/src/overlay_autogen/timestamp.rule")
set(lupdate_subproject1_excluded "")
set(lupdate_subproject1_autogen_dir "C:/Users/shche/free-pdf-editor/build_mingw/src/overlay_autogen")

set(lupdate_subproject2_source_dir "C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject2_include_paths "C:/Users/shche/free-pdf-editor/build_mingw/src/document_autogen/include;C:/Users/shche/free-pdf-editor/src;C:/Qt/6.10.2/mingw_64/include/QtCore;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/mkspecs/win32-g++;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtGui;C:/Qt/6.10.2/mingw_64/include;C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject2_sources "C:/Users/shche/free-pdf-editor/build_mingw/src/document_autogen/mocs_compilation.cpp;document/DocumentMetadata.h;document/PageModel.h;document/PageModel.cpp;document/Document.h;document/Document.cpp;C:/Users/shche/free-pdf-editor/build_mingw/src/document_autogen/timestamp;C:/Users/shche/free-pdf-editor/build_mingw/src/document_autogen/timestamp.rule")
set(lupdate_subproject2_excluded "")
set(lupdate_subproject2_autogen_dir "C:/Users/shche/free-pdf-editor/build_mingw/src/document_autogen")

set(lupdate_subproject3_source_dir "C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject3_include_paths "C:/Users/shche/free-pdf-editor/build_mingw/src/cache_autogen/include;C:/Users/shche/free-pdf-editor/src;C:/Qt/6.10.2/mingw_64/include/QtCore;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/mkspecs/win32-g++;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtGui;C:/Qt/6.10.2/mingw_64/include")
set(lupdate_subproject3_sources "C:/Users/shche/free-pdf-editor/build_mingw/src/cache_autogen/mocs_compilation.cpp;cache/PageRenderCache.h;cache/PageRenderCache.cpp;C:/Users/shche/free-pdf-editor/build_mingw/src/cache_autogen/timestamp;C:/Users/shche/free-pdf-editor/build_mingw/src/cache_autogen/timestamp.rule")
set(lupdate_subproject3_excluded "")
set(lupdate_subproject3_autogen_dir "C:/Users/shche/free-pdf-editor/build_mingw/src/cache_autogen")

set(lupdate_subproject4_source_dir "C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject4_include_paths "C:/Users/shche/free-pdf-editor/build_mingw/src/pdf_engine_autogen/include;C:/Users/shche/free-pdf-editor/src;C:/Qt/6.10.2/mingw_64/include/QtCore;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/mkspecs/win32-g++;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtGui;C:/Qt/6.10.2/mingw_64/include;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject4_sources "C:/Users/shche/free-pdf-editor/build_mingw/src/pdf_engine_autogen/mocs_compilation.cpp;pdf_engine/PdfiumBridge.h;pdf_engine/PdfiumBridge.cpp;pdf_engine/PdfRenderer.h;pdf_engine/PdfRenderer.cpp;pdf_engine/PdfWriter.h;pdf_engine/PdfWriter.cpp;C:/Users/shche/free-pdf-editor/build_mingw/src/pdf_engine_autogen/timestamp;C:/Users/shche/free-pdf-editor/build_mingw/src/pdf_engine_autogen/timestamp.rule")
set(lupdate_subproject4_excluded "")
set(lupdate_subproject4_autogen_dir "C:/Users/shche/free-pdf-editor/build_mingw/src/pdf_engine_autogen")

set(lupdate_subproject5_source_dir "C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject5_include_paths "C:/Users/shche/free-pdf-editor/build_mingw/src/ocr_autogen/include;C:/Users/shche/free-pdf-editor/src;C:/Qt/6.10.2/mingw_64/include/QtCore;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/mkspecs/win32-g++;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtGui;C:/Qt/6.10.2/mingw_64/include")
set(lupdate_subproject5_sources "C:/Users/shche/free-pdf-editor/build_mingw/src/ocr_autogen/mocs_compilation.cpp;ocr/OCRProcessor.h;ocr/OCRProcessor.cpp;C:/Users/shche/free-pdf-editor/build_mingw/src/ocr_autogen/timestamp;C:/Users/shche/free-pdf-editor/build_mingw/src/ocr_autogen/timestamp.rule")
set(lupdate_subproject5_excluded "")
set(lupdate_subproject5_autogen_dir "C:/Users/shche/free-pdf-editor/build_mingw/src/ocr_autogen")

set(lupdate_subproject6_source_dir "C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject6_include_paths "C:/Users/shche/free-pdf-editor/build_mingw/src/utils_autogen/include;C:/Users/shche/free-pdf-editor/src;C:/Qt/6.10.2/mingw_64/include/QtCore;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/mkspecs/win32-g++;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtGui;C:/Qt/6.10.2/mingw_64/include")
set(lupdate_subproject6_sources "C:/Users/shche/free-pdf-editor/build_mingw/src/utils_autogen/mocs_compilation.cpp;utils/Logger.h;utils/Logger.cpp;utils/FileUtils.h;utils/FileUtils.cpp;C:/Users/shche/free-pdf-editor/build_mingw/src/utils_autogen/timestamp;C:/Users/shche/free-pdf-editor/build_mingw/src/utils_autogen/timestamp.rule")
set(lupdate_subproject6_excluded "")
set(lupdate_subproject6_autogen_dir "C:/Users/shche/free-pdf-editor/build_mingw/src/utils_autogen")

set(lupdate_subproject7_source_dir "C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject7_include_paths "C:/Users/shche/free-pdf-editor/build_mingw/src/editor_autogen/include;C:/Users/shche/free-pdf-editor/src;C:/Qt/6.10.2/mingw_64/include/QtCore;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/mkspecs/win32-g++;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtGui;C:/Qt/6.10.2/mingw_64/include;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject7_sources "C:/Users/shche/free-pdf-editor/build_mingw/src/editor_autogen/mocs_compilation.cpp;editor/Command.h;editor/UndoStack.h;editor/UndoStack.cpp;editor/SelectionManager.h;editor/SelectionManager.cpp;editor/EditorController.h;editor/EditorController.cpp;editor/commands/AddAnnotationCommand.h;editor/commands/AddAnnotationCommand.cpp;editor/commands/AddTextEditCommand.h;editor/commands/AddTextEditCommand.cpp;editor/commands/DeletePageCommand.h;editor/commands/DeletePageCommand.cpp;editor/commands/InsertImageCommand.h;editor/commands/InsertImageCommand.cpp;editor/commands/MoveObjectCommand.h;editor/commands/MoveObjectCommand.cpp;editor/commands/ReplaceTextCommand.h;editor/commands/ReplaceTextCommand.cpp;C:/Users/shche/free-pdf-editor/build_mingw/src/editor_autogen/timestamp;C:/Users/shche/free-pdf-editor/build_mingw/src/editor_autogen/timestamp.rule")
set(lupdate_subproject7_excluded "")
set(lupdate_subproject7_autogen_dir "C:/Users/shche/free-pdf-editor/build_mingw/src/editor_autogen")

set(lupdate_subproject8_source_dir "C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject8_include_paths "C:/Users/shche/free-pdf-editor/build_mingw/src/ui_autogen/include;C:/Users/shche/free-pdf-editor/src;C:/Qt/6.10.2/mingw_64/include/QtCore;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/mkspecs/win32-g++;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtGui;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtWidgets;C:/Qt/6.10.2/mingw_64/include;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject8_sources "C:/Users/shche/free-pdf-editor/build_mingw/src/ui_autogen/mocs_compilation.cpp;ui/Toolbar.h;ui/Toolbar.cpp;ui/ThumbnailPanel.h;ui/ThumbnailPanel.cpp;ui/InspectorPanel.h;ui/InspectorPanel.cpp;ui/PageView.h;ui/PageView.cpp;ui/MainWindow.h;ui/MainWindow.cpp;C:/Users/shche/free-pdf-editor/build_mingw/src/ui_autogen/timestamp;C:/Users/shche/free-pdf-editor/build_mingw/src/ui_autogen/timestamp.rule")
set(lupdate_subproject8_excluded "")
set(lupdate_subproject8_autogen_dir "C:/Users/shche/free-pdf-editor/build_mingw/src/ui_autogen")

set(lupdate_subproject9_source_dir "C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject9_include_paths "C:/Users/shche/free-pdf-editor/build_mingw/src/app_autogen/include;C:/Users/shche/free-pdf-editor/src;C:/Qt/6.10.2/mingw_64/include/QtCore;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/mkspecs/win32-g++;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtGui;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtWidgets;C:/Qt/6.10.2/mingw_64/include;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject9_sources "C:/Users/shche/free-pdf-editor/build_mingw/src/app_autogen/mocs_compilation.cpp;app/Application.h;app/Application.cpp;C:/Users/shche/free-pdf-editor/build_mingw/src/app_autogen/timestamp;C:/Users/shche/free-pdf-editor/build_mingw/src/app_autogen/timestamp.rule")
set(lupdate_subproject9_excluded "")
set(lupdate_subproject9_autogen_dir "C:/Users/shche/free-pdf-editor/build_mingw/src/app_autogen")

set(lupdate_subproject10_source_dir "C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject10_include_paths "C:/Users/shche/free-pdf-editor/build_mingw/src/pdf-editor_autogen/include;C:/Users/shche/free-pdf-editor/src;C:/Qt/6.10.2/mingw_64/include/QtCore;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/mkspecs/win32-g++;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtGui;C:/Qt/6.10.2/mingw_64/include;C:/Qt/6.10.2/mingw_64/include/QtWidgets;C:/Qt/6.10.2/mingw_64/include;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src;C:/Users/shche/free-pdf-editor/src")
set(lupdate_subproject10_sources "C:/Users/shche/free-pdf-editor/build_mingw/src/pdf-editor_autogen/mocs_compilation.cpp;app/main.cpp;C:/Users/shche/free-pdf-editor/build_mingw/.qt/rcc/qrc_pdf-editor_translations.cpp;C:/Users/shche/free-pdf-editor/build_mingw/src/pdf-editor_autogen/timestamp;C:/Users/shche/free-pdf-editor/build_mingw/src/pdf-editor_autogen/timestamp.rule")
set(lupdate_subproject10_excluded "")
set(lupdate_subproject10_autogen_dir "C:/Users/shche/free-pdf-editor/build_mingw/src/pdf-editor_autogen")
